### PR TITLE
 getShortName refactored 

### PR DESCRIPTION
**Pull request by raunaqg**
See File [https://github.com/subahm/jenkins/core/src/main/java/hudson/ClassicPlugInStrategy.java]

**Proposed changelog entries**

Entry 1: Issue, bloater - long method. Found in ClassicPlugInStrategy.java

**Proposed upgrade guidelines**

Extracted the getShortName method and created two new methods called "validateArchive" and "getManifest". Code is cleaner, easier to read and getShortName method size has been reduced from 21 lines to 3 lines. Refactored code passes all tests.

**Submitter checklist**

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). Examples
          Fill-in the Proposed changelog entries section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x]  For dependency updates: links to external changelogs and, if possible, full diffs

**Desired reviewers**

@brookeireland
@hirron
@subahm
@zoegoodwinsutton 
@WhitneyDluhosh

**Maintainer checklist**

Before the changes are marked as ready-for-merge:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or Proposed changelog entries are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically

### CODE REVIEW

**Comment by subahm** [comment]
@raunaqg Do you want to please update the description of this PR similar to other PRs including the relevant checklists. Also, all the jenkins tests passed on this branch, right? If they did, just add a note in the description. Thanks

**Comment by raunaqg** [comment]
> @raunaqg Do you want to please update the description of this PR similar to other PRs including the relevant checklists. Also, all the jenkins tests passed on this branch, right? If they did, just add a note in the description. Thanks

The format of the description has been updated to match the format of other PR's (mine did not come with a template when I originally made my PR). Yes all tests passed on this branch, I have added a note of it in the description as required as well! Let me know if this work.

**Comment by zoegoodwinsutton** [comment]
Looks good. Nice use of extract method!

**Review by subahm — APPROVED** [review]
Looks good!

**Pull request merged**
